# docker-compose.yml

version: '3.8'

services:
  # Our Python Backend Service
  backend:
    build: . # Build the image from the Dockerfile in the current directory
    container_name: scorm-backend
    # We don't need to expose ports to the host directly,
    # as Nginx will handle communication.

  # Our Nginx Frontend Service
  frontend:
    image: nginx:1.21-alpine # Use a lightweight Nginx image
    container_name: scorm-frontend
    ports:
      - "8080:80" # Map port 8080 on your machine to port 80 in the container
    volumes:
      # Mount our HTML file and Nginx config into the container
      - ./index.html:/usr/share/nginx/html/index.html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend # Make sure the backend starts before the frontend
