# docker-compose.yml

version: '3.8'

services:
  # Our Python Backend Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scorm-backend
    volumes:
      - ./logs:/app/logs
    # --- NEW: Provide environment variables to the container ---
    environment:
      - GUNICORN_WORKERS=5 # Sets the number of workers for performance
      - AUTH0_DOMAIN=dev-b0houl2m3pgvvqbt.us.auth0.com # <-- REPLACE with your Auth0 Domain
      - API_AUDIENCE=https://scorm-processor-api   # <-- REPLACE with your API Audience

  # Our Nginx Frontend Service
  frontend:
    # --- MODIFIED: Build the frontend from our new Dockerfile ---
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: scorm-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend