# docker-compose.yml

version: '3.8'

services:
  # Our Python Backend Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scorm-backend
    volumes:
      - ./logs:/app/logs
    # --- NEW: Provide environment variables to the container ---
    env_file:
      - .env


  # Our Nginx Frontend Service
  frontend:
    # --- MODIFIED: Build the frontend from our new Dockerfile ---
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: scorm-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend