# render.yaml (Using 'routes' as requested for testing)

services:
  # The Python/Gunicorn backend.
  - type: pserv
    name: backend
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - fromGroup: scorm-app-secrets

  # The Nginx frontend.
  - type: web
    name: frontend
    env: docker
    dockerfilePath: ./frontend.Dockerfile
    healthCheckPath: /
    # --- MODIFIED: Using 'routes' instead of 'rewrites' ---
    routes:
      - type: rewrite
        source: /api/:path*
        destination: http://backend:8080/api/:path
      - type: rewrite
        source: /download/:path*
        destination: http://backend:8080/download/:path

# Define a group for secrets and environment variables
envVarGroups:
  - name: scorm-app-secrets
    envVars:
      - key: AUTH0_DOMAIN
        value: dev-b0houl2m3pgvvqbt.us.auth0.com # <-- REPLACE
      - key: API_AUDIENCE
        value: https://scorm-processor-api   # <-- REPLACE
      - key: GUNICORN_WORKERS
        value: 5
      - key: PYTHON_VERSION
        value: 3.12